alias vi='vim'
alias ls='ls --color=auto -F'
alias lr='ls -RF'
alias ll='ls -alF --time-style=long-iso'
alias sudo='sudo '
alias chrome='google-chrome'
alias suspend='systemctl suspend'
alias tree='tree -a'
alias dc='docker-compose'
alias iptables='iptables --line-numbers -v'
alias ip6tables='iptables --line-numbers -v'
