alias vi='vim'
alias ls='ls --color=auto -F'
alias lr='ls -aF'
alias lr='ls -RF'
alias ll='ls -lF --time-style=long-iso'
alias lla='ls -alF --time-style=long-iso'
alias sudo='sudo '
alias chrome='google-chrome'
alias suspend='systemctl suspend'
alias tree='tree -a'
alias dc='docker-compose'
alias ..='cd ../'
alias ...='cd ../../'
